name: rav_printer
description: Ravintola for Printer TSPL commands.
version: 0.0.3
homepage: https://github.com/maulanadiooo/rav_printer

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=1.20.0"
dependencies:
  bluetooth_thermal_printer_plus: ^0.0.2
  esc_pos_utils_plus: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null
